deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
    name: bff-app
    namespace: frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: bff-app
    template:
        metadata:
            labels:
                app: bff-app
        spec:
            containers:
                - name: bff-container
                  image: aicmsregistry.azurecr.io/bff:1.0
                  env:
                      - name: foo
                        value: bar
                  ports:
                      - containerPort: 3000