apiVersion: v1
kind: Service
metadata:
  name: bff-service
  namespace: frontend
spec:
  loadBalancerIP: 135.225.119.97
  type: LoadBalancer
  selector:
    app: bff-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
