name: Build and Push Docker Image

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          echo "https://${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials
          git config --global credential.helper store

      - name: Check and bump version
        run: |
          if [ -f VERSION ]; then
            version=$(cat VERSION)
          else
            version="0.0.0"
          fi

          # Increment patch version manually
          IFS='.' read -r major minor patch <<< "$version"
          new_version="$major.$minor.$((patch + 1))"

          # Save the new version
          echo "$new_version" > VERSION
          echo "New version: $new_version"

          # Export new version to be used later in other steps
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Bump version in package.json
        run: |
          # Bump the version in package.json (patch bump)
          npm version patch --no-git-tag-version -m "Bump version to $new_version"

      - name: Commit version bump and create tag
        run: |
          git add VERSION package.json
          git commit -m "Bump version to $new_version"
          git tag "v$new_version"  # Create a tag for the version
          git push origin deploy --tags  # Push changes and tags to the deploy branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        run: docker login "${{ secrets.DOCKER_USERNAME }}".azurecr.io -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build the Docker image
        run: docker build -t aicmsregistry.azurecr.io/bff:latest .

      - name: Push the Docker image
        run: docker push aicmsregistry.azurecr.io/bff:latest
