name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login "${{ secrets.DOCKER_USERNAME }}".azurecr.io -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build the Docker image
        run: docker build -t aicmsregistry.azurecr.io/bff:latest .

      - name: Push the Docker image
        run: docker push aicmsregistry.azurecr.io/bff:latest
